version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest HW-03a-Develop-With-Testing-in-Mind/test/test_fetch_user_repo.py
      - run: pytest HW-03b-External-Dependencies-Isolation-Mocking/test/test_fetch_user_repo.py

workflows:
  version: 2
  test:
    jobs:
      - test
