version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest HW-003a-Develop-with-Testing-in-Mind/test/test_fetch_user_repo.py

workflows:
  version: 2
  test:
    jobs:
      - test
