[project]
name = "hw-003a-develop-with-testing-in-mind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "charset-normalizer>=3.4.3",
    "pytest>=8.4.2",
    "requests>=2.32.5",
]
